app/src/main/java/com/numero/material_gallery/activity/BottomNavigationActivity.kt
app/src/main/res/layout/activity_bottom_navgation.xml

* ColorTheming が適用されていないため、BottomNavigation の色がおかしい

BottomNavigationの修正

---

app/src/main/java/com/numero/material_gallery/activity/NavigationDrawerActivity.kt
app/src/main/res/layout/app_bar_navigation_drawer.xml

* Drawer 表示のボタン追加  
* 戻るボタンの修正

NavigationDrawerの改善

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/java/com/numero/material_gallery/activity/RadioButtonActivity.kt
app/src/main/java/com/numero/material_gallery/model/DesignComponent.kt
app/src/main/res/layout/activity_radio_button.xml
app/src/main/res/values/strings.xml

RadioButtonの追加

---

app/src/main/java/com/numero/material_gallery/activity/TextFieldActivity.kt
app/src/main/res/layout/activity_text_field.xml
app/src/main/res/values/strings.xml

Error の TextInputLayout の追加

---

app/src/main/java/com/numero/material_gallery/view/ColorInfoItemView.kt
app/src/main/res/layout/view_color_info_item.xml

ColorInfo のデザイン変更

---

README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties

Updated AndroidStudio and material-components

---

app/build.gradle
app/src/main/java/com/numero/material_gallery/fragment/SettingsFragment.kt

Updated libraries

---

app/src/main/res/layout/activity_chip.xml

Fixed to be can scroll chip screen.

Fixed chip screen can be scroll

---

app/src/main/java/com/numero/material_gallery/activity/BottomNavigationActivity.kt
app/src/main/java/com/numero/material_gallery/activity/BottomSheetActivity.kt
app/src/main/java/com/numero/material_gallery/activity/CheckboxActivity.kt
app/src/main/java/com/numero/material_gallery/activity/ChipActivity.kt
app/src/main/java/com/numero/material_gallery/activity/FabActivity.kt
app/src/main/java/com/numero/material_gallery/activity/MaterialButtonActivity.kt
app/src/main/java/com/numero/material_gallery/activity/MaterialCardActivity.kt
app/src/main/java/com/numero/material_gallery/activity/ModalBottomSheetActivity.kt
app/src/main/java/com/numero/material_gallery/activity/NavigationDrawerActivity.kt
app/src/main/java/com/numero/material_gallery/activity/ProgressBarActivity.kt
app/src/main/java/com/numero/material_gallery/activity/RadioButtonActivity.kt
app/src/main/java/com/numero/material_gallery/activity/SettingsActivity.kt
app/src/main/java/com/numero/material_gallery/activity/SnackbarActivity.kt
app/src/main/java/com/numero/material_gallery/activity/SwitchActivity.kt
app/src/main/java/com/numero/material_gallery/activity/TabActivity.kt
app/src/main/java/com/numero/material_gallery/activity/TextFieldActivity.kt
app/src/main/java/com/numero/material_gallery/activity/bottom_app_bar/BottomAppBarActivity.kt
app/src/main/java/com/numero/material_gallery/activity/bottom_app_bar/BottomAppBarTypeActivity.kt
app/src/main/java/com/numero/material_gallery/activity/bottom_app_bar/HideOnScrollActivity.kt
app/src/main/java/com/numero/material_gallery/activity/top_app_bar/ActionBarActivity.kt
app/src/main/java/com/numero/material_gallery/activity/top_app_bar/CollapsingActivity.kt
app/src/main/java/com/numero/material_gallery/activity/top_app_bar/LiftOnScrollActivity.kt
app/src/main/java/com/numero/material_gallery/activity/top_app_bar/TopAppBarTypeActivity.kt

Use @ContentView instead of `setContentView`.
- close #60

Use @ContentView annotation

---

build.gradle

- I forget update release version.

Release ver1.1.0

---

app/src/main/res/drawable/bab_linear_shadow.xml
app/src/main/res/drawable/ic_dashboard.xml
app/src/main/res/drawable/ic_favorite.xml
app/src/main/res/drawable/ic_home.xml
app/src/main/res/drawable/ic_notifications.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Removed unused files

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/numero/material_gallery/fragment/SettingsFragment.kt
app/src/main/res/values/style_base.xml
app/src/main/res/values/styles.xml
app/src/main/res/xml/settings.xml
build.gradle

- Added licenses screen.
- close #66

Implemented licenses screen

---

app/src/main/java/com/numero/material_gallery/activity/MaterialCardActivity.kt
app/src/main/java/com/numero/material_gallery/model/state/card/Corner.kt
app/src/main/java/com/numero/material_gallery/model/state/card/Elevation.kt
app/src/main/java/com/numero/material_gallery/model/state/card/Stroke.kt
app/src/main/res/layout/activity_material_card.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

- Added seekbar to adjust MaterialCard stroke.
- Removed button on card.

Changed MaterialCard screen

---

README.md
build.gradle

Updated Android Studio

---

app/src/main/res/layout/view_holder_card.xml
build.gradle

- Updated material-components 1.1.0-alpha04
- Fixed build

Updated material-components library

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/java/com/numero/material_gallery/activity/ExtendedFabActivity.kt
app/src/main/java/com/numero/material_gallery/model/DesignComponent.kt
app/src/main/res/layout/activity_extended_fab.xml
app/src/main/res/values/strings.xml

Implemented Extended FAB

---

build.gradle

Release 1.2.0

---

README.md
build.gradle

- Android Studio updated 3.4.0  
- Kotlin updated 1.3.31

Updated AS and Kotlin version

---

app/src/main/java/com/numero/material_gallery/activity/TextFieldActivity.kt
app/src/main/res/layout/activity_text_field.xml

- Added custom icon pattern.  
- Added dropdown pattern.  
|Before|After|
|:--:|:--:|
| ![device-2019-05-06-173853](https://user-images.githubusercontent.com/13705006/57214734-d750ac00-7025-11e9-8ba8-4dc1ca442e0c.png) | ![device-2019-05-06-173657](https://user-images.githubusercontent.com/13705006/57214707-c43ddc00-7025-11e9-85ea-5fef1fef721e.png) |

Updated Text Field contents

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/java/com/numero/material_gallery/activity/MaterialButtonToggleGroupActivity.kt
app/src/main/java/com/numero/material_gallery/model/DesignComponent.kt
app/src/main/res/layout/activity_material_button_toggle_group.xml
app/src/main/res/values/strings.xml

Implemented MaterialButtonToggleGroup example

---

app/build.gradle
app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml

- Fixed status bar color.
- Supports API 21 higher.

Fixed status bar color

---

app/src/main/java/com/numero/material_gallery/activity/TabActivity.kt
app/src/main/res/layout/activity_tab.xml

- Implemented tab's badge sample.

Implemented tab's badge

---

app/src/main/java/com/numero/material_gallery/activity/BottomNavigationActivity.kt
app/src/main/res/layout/activity_bottom_navgation.xml

- Implemented bottom navigation's badge.

Implemented bottom navigation's badge

---

app/src/main/res/layout/activity_bottom_app_bar.xml
app/src/main/res/layout/activity_bottom_app_bar_type.xml
app/src/main/res/layout/activity_bottom_navgation.xml
app/src/main/res/layout/activity_bottom_sheet.xml
app/src/main/res/layout/activity_checkbox.xml
app/src/main/res/layout/activity_chip.xml
app/src/main/res/layout/activity_collapsing.xml
app/src/main/res/layout/activity_extended_fab.xml
app/src/main/res/layout/activity_fab.xml
app/src/main/res/layout/activity_hide_on_scroll.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_material_button.xml
app/src/main/res/layout/activity_material_button_toggle_group.xml
app/src/main/res/layout/activity_material_card.xml
app/src/main/res/layout/activity_material_dialog.xml
app/src/main/res/layout/activity_modal_bottom_sheet.xml
app/src/main/res/layout/activity_progress_bar.xml
app/src/main/res/layout/activity_radio_button.xml
app/src/main/res/layout/activity_settings.xml
app/src/main/res/layout/activity_snackbar.xml
app/src/main/res/layout/activity_switch.xml
app/src/main/res/layout/activity_tab.xml
app/src/main/res/layout/activity_text_field.xml
app/src/main/res/layout/activity_top_app_bar_type.xml
app/src/main/res/layout/app_bar_navigation_drawer.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values/style_base.xml
app/src/main/res/values/styles.xml

Fixed toolbar contents color

---

.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml

Added codeStyles

---

.github/PULL_REQUEST_TEMPLATE.md

Added pull request tmp

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/numero/material_gallery/activity/top_app_bar/ToolbarActivity.kt
app/src/main/java/com/numero/material_gallery/activity/top_app_bar/TopAppBarTypeActivity.kt
app/src/main/java/com/numero/material_gallery/model/TopAppBarType.kt
app/src/main/res/layout/activity_toolbar.xml
app/src/main/res/values/strings.xml

Added MaterialToolbar sample

---

app/src/main/AndroidManifest.xml
app/src/main/res/values-night/styles.xml
app/src/main/res/values-v23/styles.xml
app/src/main/res/values/styles.xml

- close #
-
|Before|After|
|:--:|:--:|
| ![device-2019-06-19-092054](https://user-images.githubusercontent.com/13705006/59728105-99c17e80-9273-11e9-872f-2605852e27fe.png) | ![device-2019-06-19-092021](https://user-images.githubusercontent.com/13705006/59728106-99c17e80-9273-11e9-9a93-441ff7442c52.png) |

Fixed LiftOnScroll screen's status bar color

---

.gitignore
build.gradle

Release 1.3.0

---

README.md
build.gradle

- Updated Kotlin version.  
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated kotlin

---

app/build.gradle
app/src/main/java/com/numero/material_gallery/activity/BottomNavigationActivity.kt
app/src/main/java/com/numero/material_gallery/activity/TabActivity.kt
build.gradle

- Updated material-components.
- close #
- https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha08
|Before|After|
|:--:|:--:|
|  |  |

Updated material-components

---

app/src/main/java/com/numero/material_gallery/activity/top_app_bar/ToolbarActivity.kt
app/src/main/res/layout/activity_toolbar.xml

- Added PrimarySurface Toolbar.  
- close #
-

Added PrimarySurface Toolbar

---

app/build.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated sdk version

---

app/src/main/java/com/numero/material_gallery/activity/MaterialCardActivity.kt
app/src/main/java/com/numero/material_gallery/model/state/card/Elevation.kt
app/src/main/res/layout/activity_material_card.xml
app/src/main/res/values/dimens.xml

- Set the maximum elevation value to 24dp.
- close #104 
-

Can select card elevation to 24dp

---

app/build.gradle
app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/strings.xml

- If exist newer version, notify message and update.
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Implemented In-App Updates

---

app/src/main/java/com/numero/material_gallery/MaterialGalleryApplication.kt
app/src/main/java/com/numero/material_gallery/fragment/ThemeInfoBottomSheetDialog.kt
app/src/main/java/com/numero/material_gallery/model/Theme.kt
app/src/main/java/com/numero/material_gallery/repository/ConfigRepository.kt
app/src/main/java/com/numero/material_gallery/repository/IConfigRepository.kt
app/src/main/res/drawable/ic_light.xml
app/src/main/res/drawable/ic_night.xml
app/src/main/res/layout/bottom_sheet_fragment_theme_info.xml

Switch theme from info

---

app/src/main/java/com/numero/material_gallery/activity/SettingsActivity.kt
app/src/main/java/com/numero/material_gallery/fragment/SettingsFragment.kt
app/src/main/res/drawable/ic_attention.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/settings.xml

- Can update from settings screen.  
- close #
-

Update from settings screen

---

app/src/main/java/com/numero/material_gallery/MainActivity.kt

- Fixed a crash when updating in top screen after canceling the update in settings screen.
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed crash when update

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/java/com/numero/material_gallery/activity/DatePickerActivity.kt
app/src/main/java/com/numero/material_gallery/model/DesignComponent.kt
app/src/main/res/layout/activity_date_picker.xml
app/src/main/res/values/strings.xml

- Added MaterialDatePicker example.  
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Added date picker

---

app/src/main/java/com/numero/material_gallery/fragment/SettingsFragment.kt
app/src/main/res/xml/settings.xml

- Added version item.
If need update, version item's text and icon change.  
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Changed need update design

---

build.gradle

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.4.0

---

app/build.gradle
build.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Cleaned gradle

---

app/build.gradle
app/src/main/res/layout/activity_settings.xml
build.gradle

- Updated AndroidX libraries.  
- Replace FragmentContainerView.  
- close #
- https://developer.android.com/jetpack/androidx/releases/#august_7_2019  
|Before|After|
|:--:|:--:|
|  |  |

Updated androidx libraries

---

README.md
build.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated AndroidStudio

---

app/src/main/java/com/numero/material_gallery/activity/DatePickerActivity.kt
build.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated material components

---

.github/workflows/android.yml

- Run CI when created PR.  
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Created actions yml

---

build.gradle

- Updated material components 1.1.0-beta01
- close #
- https://github.com/material-components/material-components-android/releases/tag/1.1.0-beta01
|Before|After|
|:--:|:--:|
|  |  |

Updated material components library

---

build.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.4.1

---

build.gradle

- Updated material component library to 1.2.0-alpha01
- close #
- https://github.com/material-components/material-components-android/releases/tag/1.2.0-alpha01
|Before|After|
|:--:|:--:|
|  |  |

Updated material component

---

README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties

- Updated Android Studio to 3.6.0 beta1
- Updated ConstraintLayout to beta3
- close #
- https://androidstudio.googleblog.com/2019/10/android-studio-36-beta-1-available.html
- https://androidstudio.googleblog.com/2019/10/constraintlayout-200-beta-3.html
|Before|After|
|:--:|:--:|
|  |  |

Updated android studio and ConstraintLayout

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/java/com/numero/material_gallery/activity/SliderActivity.kt
app/src/main/java/com/numero/material_gallery/model/DesignComponent.kt
app/src/main/res/layout/activity_slider.xml
app/src/main/res/values/strings.xml

- Added slider example.
- close #
-

Added Slider example

---

app/src/main/res/layout/activity_bottom_app_bar.xml

- Fixed an issue where BAB might cover content.
- close #133 
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed issue #133

---

app/src/main/res/layout/activity_material_button_toggle_group.xml

Added vertical MaterialButtonToggleGroup

---

build.gradle

- Release 1.5.0  
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.5.0

---

app/build.gradle
build.gradle

- Added play:core-ktx.
- Cleaned gradle.  
- close #
- https://developer.android.com/reference/com/google/android/play/core/release-notes#1-6-4
|Before|After|
|:--:|:--:|
|  |  |

Added play:core-ktx

---

app/src/main/java/com/numero/material_gallery/fragment/ThemeInfoBottomSheetDialog.kt
app/src/main/res/layout/bottom_sheet_fragment_theme_info.xml

- Replace required selection implementation with `selectionRequired`.  
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Replace required selection implementation

---

build.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.5.1

---

README.md
build.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated kotlin version

---

app/src/main/java/com/numero/material_gallery/activity/SliderActivity.kt
build.gradle

- close #
- https://github.com/material-components/material-components-android/releases/tag/1.2.0-alpha04
|Before|After|
|:--:|:--:|
|  |  |

Updated material-component

---

app/src/main/java/com/numero/material_gallery/activity/BottomSheetActivity.kt
app/src/main/res/layout/activity_bottom_sheet.xml

- Added draggable option.
- Fixed bottom sheet style.  
- Removed FAB because BottomSheet has higher elevation than FAB.  
- close #
-

Enhanced BottomSheet sample

---

app/src/main/res/layout/activity_bottom_sheet.xml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed bottom sheet text

---

build.gradle

- Release 1.5.2
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.5.2

---

gradle/wrapper/gradle-wrapper.properties

- Use `all` gradle instead of `bin`.  
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed gradle version

---

app/src/main/java/com/numero/material_gallery/activity/SliderActivity.kt
app/src/main/res/layout/activity_slider.xml
app/src/main/res/values/array.xml

Added RangeSlider example

---

build.gradle

- Bump up oss-licenses-plugin version to 0.10.2
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated oss-licenses-plugin

---

app/src/main/java/com/numero/material_gallery/activity/BottomNavigationActivity.kt
app/src/main/java/com/numero/material_gallery/activity/BottomSheetActivity.kt
app/src/main/java/com/numero/material_gallery/activity/CheckboxActivity.kt
app/src/main/java/com/numero/material_gallery/activity/ChipActivity.kt
app/src/main/java/com/numero/material_gallery/activity/DatePickerActivity.kt
app/src/main/java/com/numero/material_gallery/activity/ExtendedFabActivity.kt
app/src/main/java/com/numero/material_gallery/activity/FabActivity.kt
app/src/main/java/com/numero/material_gallery/activity/MaterialButtonActivity.kt
app/src/main/java/com/numero/material_gallery/activity/MaterialButtonToggleGroupActivity.kt
app/src/main/java/com/numero/material_gallery/activity/MaterialCardActivity.kt
app/src/main/java/com/numero/material_gallery/activity/MaterialDialogActivity.kt
app/src/main/java/com/numero/material_gallery/activity/ModalBottomSheetActivity.kt
app/src/main/java/com/numero/material_gallery/activity/NavigationDrawerActivity.kt
app/src/main/java/com/numero/material_gallery/activity/ProgressBarActivity.kt
app/src/main/java/com/numero/material_gallery/activity/RadioButtonActivity.kt
app/src/main/java/com/numero/material_gallery/activity/ShapeableImageViewActivity.kt
app/src/main/java/com/numero/material_gallery/activity/SliderActivity.kt
app/src/main/java/com/numero/material_gallery/activity/SnackbarActivity.kt
app/src/main/java/com/numero/material_gallery/activity/SwitchActivity.kt
app/src/main/java/com/numero/material_gallery/activity/TabActivity.kt
app/src/main/java/com/numero/material_gallery/activity/TextFieldActivity.kt
app/src/main/java/com/numero/material_gallery/activity/bottom_app_bar/BottomAppBarActivity.kt
app/src/main/java/com/numero/material_gallery/activity/bottom_app_bar/HideOnScrollActivity.kt
app/src/main/java/com/numero/material_gallery/activity/top_app_bar/ActionBarActivity.kt
app/src/main/java/com/numero/material_gallery/activity/top_app_bar/CollapsingActivity.kt
app/src/main/java/com/numero/material_gallery/activity/top_app_bar/ToolbarActivity.kt
app/src/main/java/com/numero/material_gallery/fragment/BottomSheetModalFragment.kt
app/src/main/java/com/numero/material_gallery/fragment/ThemeInfoBottomSheetDialog.kt

- Title says it all.    
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Cleaned BottomSheetDialogFramgent code

---

app/src/main/java/com/numero/material_gallery/components/card/MaterialCardActivity.kt
app/src/main/res/layout/activity_material_card.xml

- Replace Seekbar with Slider in card example.
- close #
-
|Before|After|
|:--:|:--:|
| ![device-2020-06-27-162853](https://user-images.githubusercontent.com/13705006/85917226-4f65db00-b893-11ea-928a-e60dcab84f84.png) | ![device-2020-06-27-162744](https://user-images.githubusercontent.com/13705006/85917206-2b09fe80-b893-11ea-9fe7-05be5a1c3b1f.png) |

Updated card example

---

app/src/main/res/layout/activity_bottom_app_bar.xml
app/src/main/res/layout/activity_bottom_navgation.xml
app/src/main/res/layout/activity_chip.xml
app/src/main/res/layout/activity_date_picker.xml
app/src/main/res/layout/activity_extended_fab.xml
app/src/main/res/layout/activity_fab.xml
app/src/main/res/layout/activity_material_button.xml
app/src/main/res/layout/activity_material_button_toggle_group.xml
app/src/main/res/layout/activity_material_card.xml
app/src/main/res/layout/activity_progress_indicator.xml
app/src/main/res/layout/activity_shapeable_image_view.xml
app/src/main/res/layout/activity_slider.xml
app/src/main/res/layout/activity_tab.xml
app/src/main/res/layout/activity_text_field.xml
app/src/main/res/layout/view_color_info_item.xml
app/src/main/res/layout/view_holder_item.xml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Use typography theming

---

build.gradle

- Release 1.5.3
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.5.3

---

app/src/main/res/values-night/styles.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Use statusBar color of primaryVariant or surface

---

app/src/main/res/layout/fragment_progress_indicator.xml
app/src/main/res/layout/fragment_text_field.xml

- close #180
-
|Before|After|
|:--:|:--:|
|  |  |

Use MaterialAutoCompleteTextView instead of AppCompatAutoCompleteTextView

---

build.gradle

-
- close #
- https://androidstudio.googleblog.com/2020/07/constraintlayout-200-beta-8.html
|Before|After|
|:--:|:--:|
|  |  |

Updated ConstraintLayout

---

.github/workflows/build.yml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Changed check build action

---

app/src/main/java/com/numero/material_gallery/components/appbar/top/TopAppBarTypeFragment.kt
app/src/main/java/com/numero/material_gallery/components/list/ComponentListAdapter.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Cleaned code

---

.github/workflows/danger.yml
Dangerfile
Gemfile
Gemfile.lock

- Setup danger on GitHub Actions.  
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Setup danger on GitHub Actions

---

.github/workflows/danger.yml
Dangerfile

- The setting of danger-android_lint was missing in #197 .  
- close #
- 
|Before|After|
|:--:|:--:|
|  |  |

Added setting of danger-android_lint

---

app/src/main/java/com/numero/material_gallery/components/DesignComponent.kt
app/src/main/java/com/numero/material_gallery/components/list/ComponentListAdapter.kt
app/src/main/java/com/numero/material_gallery/components/list/ComponentListFragment.kt
app/src/main/java/com/numero/material_gallery/components/picker/date/DatePickerFragment.kt
app/src/main/java/com/numero/material_gallery/components/picker/time/TimePickerFragment.kt
app/src/main/res/layout/fragment_time_picker.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/transition_names.xml

- Added TimePicker example.  
- Moved package.  
- close #
-

Added TimePicker example

---

app/src/main/java/com/numero/material_gallery/components/appbar/bottom/BottomAppBarFragment.kt
app/src/main/java/com/numero/material_gallery/components/bottomnavigation/BottomNavigationFragment.kt
app/src/main/java/com/numero/material_gallery/components/button/MaterialButtonFragment.kt
app/src/main/java/com/numero/material_gallery/components/button/MaterialButtonToggleGroupFragment.kt
app/src/main/java/com/numero/material_gallery/components/card/MaterialCardFragment.kt
app/src/main/java/com/numero/material_gallery/components/chip/ChipFragment.kt
app/src/main/java/com/numero/material_gallery/components/image/ShapeableImageViewFragment.kt
app/src/main/java/com/numero/material_gallery/components/list/ComponentListFragment.kt
app/src/main/java/com/numero/material_gallery/components/progressindicator/ProgressIndicatorFragment.kt
app/src/main/java/com/numero/material_gallery/components/textfield/TextFieldFragment.kt
app/src/main/java/com/numero/material_gallery/core/Extensions.kt
app/src/main/res/layout/fragment_bottom_app_bar.xml
app/src/main/res/layout/fragment_bottom_navigation.xml
app/src/main/res/layout/fragment_chip.xml
app/src/main/res/layout/fragment_material_button.xml
app/src/main/res/layout/fragment_material_button_toggle_group.xml
app/src/main/res/layout/fragment_material_card.xml
app/src/main/res/layout/fragment_progress_indicator.xml
app/src/main/res/layout/fragment_shapeable_image_view.xml
app/src/main/res/layout/fragment_text_field.xml

- It might be good to use insetter 🤔 
https://github.com/chrisbanes/insetter
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed window inset

---

app/src/main/res/layout/fragment_collapsing.xml
app/src/main/res/values/strings.xml

Updated Collapsing to multiline

---

app/src/main/java/com/numero/material_gallery/components/MaterialContainerTransformFragment.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed flickering when container transition

---

build.gradle

- Release 1.6.0
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.6.0

---

app/src/main/java/com/numero/material_gallery/components/list/ComponentListFragment.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed settings screen transition anim

---

app/src/main/java/com/numero/material_gallery/components/progressindicator/ProgressIndicatorFragment.kt
app/src/main/res/layout/fragment_progress_indicator.xml
app/src/main/res/values/dimens.xml

Added chip on progress indicator sample

---

.idea/codeStyles/Project.xml

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated Project.xml

---

app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/res/values-night/themes.xml
app/src/main/res/values/themes.xml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Cleaned setup statusbar

---

app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/res/values-night/themes.xml
app/src/main/res/values/themes.xml

Reverts NUmeroAndDev/MaterialGallery-android#235

Revert "Cleaned setup statusbar"

---

app/src/main/java/com/numero/material_gallery/components/appbar/bottom/BottomAppBarFragment.kt
app/src/main/java/com/numero/material_gallery/components/navigationdrawer/NavigationDrawerFragment.kt
app/src/main/java/com/numero/material_gallery/core/BottomAppBarEdgeTreatment.kt

Fixed BottomAppBar top edge when cut shape FloatingActionButton

---

app/src/main/java/com/numero/material_gallery/components/progressindicator/ProgressIndicatorFragment.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed chip with ProgressIndicator

---

build.gradle

- Release 1.6.1
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.6.1

---

app/src/main/java/com/numero/material_gallery/components/fab/ExtendedFabFragment.kt
app/src/main/java/com/numero/material_gallery/components/fab/FabFragment.kt
app/src/main/res/layout/fragment_extended_fab.xml
app/src/main/res/layout/fragment_fab.xml

- Added show/hide animation at FAB and ExtendedFAB.
- close #
-

Added show/hide animation at FAB

---

build.gradle

- Release 1.6.2
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.6.2

---

app/build.gradle

- #279 
-
|Before|After|
|:--:|:--:|
|  |  |

Enable ViewBinding

---

app/src/main/java/com/numero/material_gallery/components/progressindicator/ProgressIndicatorFragment.kt

- Title says it all. 
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed show/hide rounded progress indicator

---

build.gradle

- Release 1.6.3
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 1.6.3

---

.github/workflows/code-format-suggest.yml
build.gradle

- ktlint + Spotless + GitHub Actions
- close #
- https://qiita.com/takahirom/items/2a3d2912e74107748765
|Before|After|
|:--:|:--:|
|  |  |

Setup spotless and suggest code format

---

.github/workflows/build.yml
.github/workflows/danger.yml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed GitHub Actions when run danger

---

app/src/main/java/com/numero/material_gallery/components/MaterialContainerTransformFragment.kt
app/src/main/java/com/numero/material_gallery/components/appbar/bottom/BottomAppBarFragment.kt
app/src/main/java/com/numero/material_gallery/components/appbar/top/ActionBarFragment.kt
app/src/main/java/com/numero/material_gallery/components/appbar/top/CollapsingFragment.kt
app/src/main/java/com/numero/material_gallery/components/appbar/top/ToolbarFragment.kt
app/src/main/java/com/numero/material_gallery/components/appbar/top/TopAppBarTypeFragment.kt
app/src/main/java/com/numero/material_gallery/components/bottomnavigation/BottomNavigationFragment.kt
app/src/main/java/com/numero/material_gallery/components/button/MaterialButtonFragment.kt
app/src/main/java/com/numero/material_gallery/components/button/MaterialButtonToggleGroupFragment.kt
app/src/main/java/com/numero/material_gallery/components/card/MaterialCardFragment.kt
app/src/main/java/com/numero/material_gallery/components/chip/ChipFragment.kt
app/src/main/java/com/numero/material_gallery/components/dialog/MaterialDialogFragment.kt
app/src/main/java/com/numero/material_gallery/components/fab/ExtendedFabFragment.kt
app/src/main/java/com/numero/material_gallery/components/fab/FabFragment.kt
app/src/main/java/com/numero/material_gallery/components/image/ShapeableImageViewFragment.kt
app/src/main/java/com/numero/material_gallery/components/list/ComponentListFragment.kt
app/src/main/java/com/numero/material_gallery/components/navigationdrawer/NavigationDrawerFragment.kt
app/src/main/java/com/numero/material_gallery/components/picker/date/DatePickerFragment.kt
app/src/main/java/com/numero/material_gallery/components/picker/time/TimePickerFragment.kt
app/src/main/java/com/numero/material_gallery/components/progressindicator/ProgressIndicatorFragment.kt
app/src/main/java/com/numero/material_gallery/components/selection/CheckboxFragment.kt
app/src/main/java/com/numero/material_gallery/components/selection/RadioButtonFragment.kt
app/src/main/java/com/numero/material_gallery/components/selection/SwitchFragment.kt
app/src/main/java/com/numero/material_gallery/components/sheet/BottomSheetFragment.kt
app/src/main/java/com/numero/material_gallery/components/sheet/ModalBottomSheetFragment.kt
app/src/main/java/com/numero/material_gallery/components/slider/SliderFragment.kt
app/src/main/java/com/numero/material_gallery/components/snackbar/SnackbarFragment.kt
app/src/main/java/com/numero/material_gallery/components/tab/TabFragment.kt
app/src/main/java/com/numero/material_gallery/components/textfield/TextFieldFragment.kt
app/src/main/java/com/numero/material_gallery/settings/SettingsFragment.kt

Just replace `ViewBinding.inflate(...)` with `ViewBinding.bind(...)` to get rid of unnecessary `onCreateView` method

ViewBinding enhancements

---

gradle/wrapper/gradle-wrapper.properties

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Bump gradle version to 6.8

---

studies/reply/src/main/res/color/bottom_navigation_tint.xml
studies/reply/src/main/res/values/styles.xml
studies/reply/src/main/res/values/themes.xml

- close #
-
|Before|After|
|:--:|:--:|
| ![device-2021-01-14-203938](https://user-images.githubusercontent.com/13705006/104586311-a785f280-56a8-11eb-9de2-476294c767f1.png) | ![device-2021-01-14-203850](https://user-images.githubusercontent.com/13705006/104586296-a48b0200-56a8-11eb-9fd3-da3c71925282.png) |

[Reply]Fixed BottomNavigation style

---

app/build.gradle
app/src/main/java/com/numero/material_gallery/components/appbar/bottom/BottomAppBarFragment.kt
app/src/main/java/com/numero/material_gallery/components/appbar/top/CollapsingFragment.kt
app/src/main/java/com/numero/material_gallery/components/bottomnavigation/BottomNavigationFragment.kt
app/src/main/java/com/numero/material_gallery/components/button/MaterialButtonFragment.kt
app/src/main/java/com/numero/material_gallery/components/button/MaterialButtonToggleGroupFragment.kt
app/src/main/java/com/numero/material_gallery/components/card/MaterialCardFragment.kt
app/src/main/java/com/numero/material_gallery/components/chip/ChipFragment.kt
app/src/main/java/com/numero/material_gallery/components/fab/ExtendedFabFragment.kt
app/src/main/java/com/numero/material_gallery/components/fab/FabFragment.kt
app/src/main/java/com/numero/material_gallery/components/image/ShapeableImageViewFragment.kt
app/src/main/java/com/numero/material_gallery/components/list/ComponentListFragment.kt
app/src/main/java/com/numero/material_gallery/components/navigationdrawer/NavigationDrawerFragment.kt
app/src/main/java/com/numero/material_gallery/components/progressindicator/ProgressIndicatorFragment.kt
app/src/main/java/com/numero/material_gallery/components/slider/SliderFragment.kt
app/src/main/java/com/numero/material_gallery/components/snackbar/SnackbarFragment.kt
app/src/main/java/com/numero/material_gallery/components/textfield/TextFieldFragment.kt
app/src/main/java/com/numero/material_gallery/settings/SettingsFragment.kt
app/src/main/java/com/numero/material_gallery/studies/StudiesFragment.kt
build.gradle
core/src/main/java/com/numero/material_gallery/core/Extensions.kt
studies/base/build.gradle
studies/base/src/main/java/com/numero/material_gallery/studies/base/ComponentGalleryFragment.kt
studies/base/src/main/res/layout/fragment_component_gallery.xml

- close #207
- https://github.com/chrisbanes/insetter
|Before|After|
|:--:|:--:|
|  |  |

Setup and replaced insetter

---

gradle.properties

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Goodbye jetifier

---

build.gradle

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 2.0.0

---

.github/dependabot.yml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Config dependabot

---

.idea/codeStyles/Project.xml
app/src/main/java/com/numero/material_gallery/components/appbar/bottom/BottomAppBarFragment.kt
app/src/main/java/com/numero/material_gallery/components/appbar/top/CollapsingFragment.kt
app/src/main/java/com/numero/material_gallery/components/bottomnavigation/BottomNavigationFragment.kt
app/src/main/java/com/numero/material_gallery/components/button/MaterialButtonFragment.kt
app/src/main/java/com/numero/material_gallery/components/button/MaterialButtonToggleGroupFragment.kt
app/src/main/java/com/numero/material_gallery/components/card/MaterialCardFragment.kt
app/src/main/java/com/numero/material_gallery/components/chip/ChipFragment.kt
app/src/main/java/com/numero/material_gallery/components/fab/ExtendedFabFragment.kt
app/src/main/java/com/numero/material_gallery/components/fab/FabFragment.kt
app/src/main/java/com/numero/material_gallery/components/image/ShapeableImageViewFragment.kt
app/src/main/java/com/numero/material_gallery/components/list/ComponentListFragment.kt
app/src/main/java/com/numero/material_gallery/components/navigationdrawer/NavigationDrawerFragment.kt
app/src/main/java/com/numero/material_gallery/components/progressindicator/ProgressIndicatorFragment.kt
app/src/main/java/com/numero/material_gallery/components/slider/SliderFragment.kt
app/src/main/java/com/numero/material_gallery/components/snackbar/SnackbarFragment.kt
app/src/main/java/com/numero/material_gallery/components/textfield/TextFieldFragment.kt
app/src/main/java/com/numero/material_gallery/settings/SettingsFragment.kt
app/src/main/java/com/numero/material_gallery/studies/StudiesFragment.kt
studies/base/src/main/java/com/numero/material_gallery/studies/base/ComponentGalleryFragment.kt

- Replaced to `WindowInsets.Type`
- close #
- https://github.com/chrisbanes/insetter/releases/tag/v0.5.0
|Before|After|
|:--:|:--:|
|  |  |

Replaced deprecated insetter

---

core/build.gradle
studies/base/build.gradle
studies/reply/build.gradle
studies/shrine/build.gradle

- 
- close #
- https://medium.com/dipien/10-great-ideas-to-improve-your-gradle-build-times-2a6b281c69c6
|Before|After|
|:--:|:--:|
|  |  |

Disable buildConfig in library module

---

app/src/main/java/com/numero/material_gallery/components/appbar/top/ToolbarFragment.kt

- Title says at all.
- close #
-

Show badge at Toolbar

---

studies/base/src/main/res/layout/fragment_component_gallery.xml
studies/shrine/src/main/res/values/styles.xml
studies/shrine/src/main/res/values/themes.xml

Added NavigationRail in Studies

---

README.md
app/build.gradle
build.gradle
core/build.gradle
gradle.properties
studies/base/build.gradle
studies/reply/build.gradle
studies/shrine/build.gradle

- Cleaned gradle file.
- Restored Fragment 1.3.4 because has issue when shared element transition.
https://issuetracker.google.com/issues/188457866
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Clean gradle file and some refactoring

---

app/src/main/res/layout/fragment_material_button.xml
app/src/main/res/layout/fragment_material_button_toggle_group.xml
app/src/main/res/values/styles.xml

- Renamed from Raised Button to Contained Button .
- Updated Material Button Toggle Group example.
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated button example

---

app/src/main/java/com/numero/material_gallery/components/textfield/TextFieldFragment.kt
app/src/main/res/layout/fragment_text_field.xml
app/src/main/res/values/strings.xml

- Added some TextField examples.
- Updated example screen.  
- close #
-
|Before|After|
|:--:|:--:|
| ![device-2021-05-21-120955](https://user-images.githubusercontent.com/13705006/119076415-7a1dcc80-ba2d-11eb-90ae-a91ea44e8544.png) | ![device-2021-05-21-120917](https://user-images.githubusercontent.com/13705006/119076377-696d5680-ba2d-11eb-9c26-49635c65a31a.png) |

Updated TextField example

---

app/src/main/java/com/numero/material_gallery/components/DesignComponent.kt
app/src/main/java/com/numero/material_gallery/components/list/ComponentListAdapter.kt
app/src/main/java/com/numero/material_gallery/components/list/ComponentListFragment.kt
app/src/main/java/com/numero/material_gallery/components/menu/MenuFragment.kt
app/src/main/res/layout/fragment_menu.xml
app/src/main/res/menu/menu_icon_popup.xml
app/src/main/res/menu/menu_overflow.xml
app/src/main/res/menu/menu_popup.xml
app/src/main/res/navigation/nav_components.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/transition_names.xml

- Added menu example.
- close #419
-

Added menu example

---

build.gradle

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 2.1

---

README.md
build.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Bump AGP version to 7.0.0-beta2

---

app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/java/com/numero/material_gallery/components/bottomnavigation/BottomNavigationFragment.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed deprecated method

---

app/src/main/java/com/numero/material_gallery/view/ColorInfoItemView.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Resolve deprecated method

---

app/build.gradle
app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/java/com/numero/material_gallery/repository/ConfigRepository.kt
app/src/main/java/com/numero/material_gallery/repository/ConfigRepositoryImpl.kt
build.gradle
core/build.gradle
core/src/main/java/com/numero/material_gallery/core/Extensions.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Replaced LiveData with coroutine flow

---

build.gradle

- Revert #431 
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Revert bump appcompat version to 1.3.0-rc01

---

app/build.gradle
app/src/main/java/com/numero/material_gallery/AppModule.kt
app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/java/com/numero/material_gallery/MaterialGalleryApplication.kt
app/src/main/java/com/numero/material_gallery/settings/SettingsFragment.kt
app/src/main/java/com/numero/material_gallery/themeinfo/ThemeInfoBottomSheetDialog.kt
build.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Replaced with hilt

---

app/src/main/java/com/numero/material_gallery/MainActivity.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Cleaned hide AppBar code

---

app/src/main/java/com/numero/material_gallery/themeinfo/ThemeInfoBottomSheetDialog.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Removed unused code

---

.idea/codeStyles/Project.xml
components/src/main/java/com/numero/material_gallery/components/appbar/top/ToolbarFragment.kt
components/src/main/res/layout/fragment_toolbar.xml

Implemented switch center title of Toolbar

---

app/src/main/java/com/numero/material_gallery/settings/SettingsFragment.kt
app/src/main/java/com/numero/material_gallery/studies/StudiesFragment.kt
components/src/main/java/com/numero/material_gallery/components/ComponentListFragment.kt
core/src/main/java/com/numero/material_gallery/core/MaterialContainerTransformFragment.kt
studies/base/src/main/java/com/numero/material_gallery/studies/base/ComponentGalleryFragment.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed transition import

---

components/src/main/java/com/numero/material_gallery/components/ComponentListAdapter.kt
components/src/main/java/com/numero/material_gallery/components/ComponentListFragment.kt
components/src/main/java/com/numero/material_gallery/components/MaterialComponent.kt
components/src/main/java/com/numero/material_gallery/components/divider/DividerFragment.kt
components/src/main/res/layout/fragment_divider.xml
components/src/main/res/navigation/nav_components.xml
components/src/main/res/values/strings.xml
components/src/main/res/values/transition_names.xml

- Added Divider component example
- close #
-

Added Divider component

---

gradle.properties

- `kotlin.parallel.tasks.in.project` is deprecated.
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Removed deprecated property

---

build.gradle

- Updating the library to alpha fixed the crash.
- close #482
-
|Before|After|
|:--:|:--:|
|  |  |

Use jetpack alpha libraries

---

build.gradle

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Release 2.2

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/java/com/numero/material_gallery/repository/ConfigRepositoryImpl.kt
app/src/main/res/values-night/themes.xml
app/src/main/res/values/themes.xml
build.gradle

- Implemented splash screen api.
- close #
- https://developer.android.com/about/versions/12/splash-screen-migration
- Android 8.1
https://user-images.githubusercontent.com/13705006/129435759-b37405ca-7d2e-4308-9848-5d807b395c4d.mp4
- Android 12
https://user-images.githubusercontent.com/13705006/129435762-d6631c41-9750-4456-a414-d1e62b1f0dfe.mp4

Implemented splash api

---

.git-pr-release
.github/workflows/code-format-suggest.yml
.github/workflows/git-pr-release.yml
build.gradle

- close #
- https://github.com/x-motemen/git-pr-release
- https://qiita.com/astronoka/items/197d9f05f21193154b8c
|Before|After|
|:--:|:--:|
|  |  |

Setup git-pr-release

---

.github/workflows/git-pr-release.yml

- Fix #491
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed git-pr-release templete

---

.github/workflows/code-format-suggest.yml
.github/workflows/danger.yml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Do not run CI when release PR

---

app/build.gradle
components/build.gradle
settings.gradle
studies/base/build.gradle
studies/crane/build.gradle
studies/reply/build.gradle
studies/shrine/build.gradle

- close #
- https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors
|Before|After|
|:--:|:--:|
|  |  |

Enable type-safe project dependencies

---

components/src/main/java/com/numero/material_gallery/components/ComponentListFragment.kt
components/src/main/java/com/numero/material_gallery/components/appbar/bottom/BottomAppBarFragment.kt
components/src/main/java/com/numero/material_gallery/components/appbar/top/ActionBarFragment.kt
components/src/main/java/com/numero/material_gallery/components/appbar/top/ToolbarFragment.kt
components/src/main/java/com/numero/material_gallery/components/bottomnavigation/BottomNavigationFragment.kt
components/src/main/java/com/numero/material_gallery/components/button/MaterialButtonFragment.kt
components/src/main/java/com/numero/material_gallery/components/button/MaterialButtonToggleGroupFragment.kt
components/src/main/java/com/numero/material_gallery/components/card/MaterialCardFragment.kt
components/src/main/java/com/numero/material_gallery/components/chip/ChipFragment.kt
components/src/main/java/com/numero/material_gallery/components/dialog/MaterialDialogFragment.kt
components/src/main/java/com/numero/material_gallery/components/divider/DividerFragment.kt
components/src/main/java/com/numero/material_gallery/components/fab/ExtendedFabFragment.kt
components/src/main/java/com/numero/material_gallery/components/fab/FabFragment.kt
components/src/main/java/com/numero/material_gallery/components/image/ShapeableImageViewFragment.kt
components/src/main/java/com/numero/material_gallery/components/menu/MenuFragment.kt
components/src/main/java/com/numero/material_gallery/components/navigationrail/NavigationRailFragment.kt
components/src/main/java/com/numero/material_gallery/components/picker/date/DatePickerFragment.kt
components/src/main/java/com/numero/material_gallery/components/picker/time/TimePickerFragment.kt
components/src/main/java/com/numero/material_gallery/components/progressindicator/ProgressIndicatorFragment.kt
components/src/main/java/com/numero/material_gallery/components/selection/CheckboxFragment.kt
components/src/main/java/com/numero/material_gallery/components/selection/RadioButtonFragment.kt
components/src/main/java/com/numero/material_gallery/components/selection/SwitchFragment.kt
components/src/main/java/com/numero/material_gallery/components/sheet/BottomSheetFragment.kt
components/src/main/java/com/numero/material_gallery/components/sheet/ModalBottomSheetFragment.kt
components/src/main/java/com/numero/material_gallery/components/slider/SliderFragment.kt
components/src/main/java/com/numero/material_gallery/components/snackbar/SnackbarFragment.kt
components/src/main/java/com/numero/material_gallery/components/tab/TabFragment.kt
components/src/main/java/com/numero/material_gallery/components/textfield/TextFieldFragment.kt
core/src/main/java/com/numero/material_gallery/core/MaterialContainerTransformFragment.kt

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed crash when switched theme

---

components/src/main/java/com/numero/material_gallery/components/appbar/top/ToolbarFragment.kt
components/src/main/res/layout/fragment_toolbar.xml

- Updated TopAppBar example.
- #506
-
|Before|After|
|:--:|:--:|
| ![Screenshot_20210901_211952](https://user-images.githubusercontent.com/13705006/131670069-33884750-94ec-4b4f-860a-ab409578cacd.png) | ![Screenshot_20210901_211700](https://user-images.githubusercontent.com/13705006/131670029-f1ab56ea-51a0-4fd0-b96c-398b271d1bf7.png) |

Updated TopAppBar example

---

components/src/main/java/com/numero/material_gallery/components/bottomnavigation/BottomNavigationFragment.kt
components/src/main/res/layout/fragment_bottom_navigation.xml

-
- #506
-
|Before|After|
|:--:|:--:|
|  | ![Screenshot_20210901_211643](https://user-images.githubusercontent.com/13705006/131670164-5be4cdfc-9004-4623-b95f-84db73a0f66d.png) |

Updated BottomNavigation example

---

components/src/main/res/layout/fragment_chip.xml

-  Updated Chip example.
- #507 
-
|Before|After|
|:--:|:--:|
| ![Screenshot_20210901_211809](https://user-images.githubusercontent.com/13705006/131669862-2344ace5-1532-4ea2-a990-0afec74a2f5d.png) | ![Screenshot_20210901_211625](https://user-images.githubusercontent.com/13705006/131669817-2a0e447a-e62f-4112-aa20-66f311581a01.png) |

Updated Chip example

---

components/src/main/java/com/numero/material_gallery/components/fab/ExtendedFabFragment.kt
components/src/main/java/com/numero/material_gallery/components/fab/FabFragment.kt
components/src/main/res/layout/fragment_extended_fab.xml
components/src/main/res/layout/fragment_fab.xml

- Updated FAB end ExtendedFAB example.
- #507
-
|Before|After|
|:--:|:--:|
| ![Screenshot_20210901_214024](https://user-images.githubusercontent.com/13705006/131672835-0ec9193b-a663-459c-af5a-5986fe911df7.png) |![Screenshot_20210901_213237](https://user-images.githubusercontent.com/13705006/131672823-b1ae5245-069b-4c1e-ab34-7686f4033a58.png)  |
| ![Screenshot_20210901_214037](https://user-images.githubusercontent.com/13705006/131672840-fefe4d71-2ec2-4b45-8cdf-a6eb0d793dbc.png) | ![Screenshot_20210901_213941](https://user-images.githubusercontent.com/13705006/131672832-9ad3fe30-6cdd-414e-a06a-a0024ab17d76.png) |

Updated FAB example

---

components/src/main/res/layout/fragment_tab.xml

- Updated Tab example.
- #507
-
|Before|After|
|:--:|:--:|
| ![Screenshot_20210901_220251](https://user-images.githubusercontent.com/13705006/131675949-1404eee5-ca57-4de6-94dd-d4aeb97fcc6d.png) | ![Screenshot_20210901_220209](https://user-images.githubusercontent.com/13705006/131675874-36c9a5b1-a288-46a9-8dd5-9519136e8a3e.png) |

Updated Tab example

---

components/src/main/res/layout/fragment_bottom_navigation.xml

- Fixed label.
- Updated label text style.
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed BottomNavigation example

---

components/src/main/java/com/numero/material_gallery/components/appbar/top/ToolbarFragment.kt
components/src/main/res/layout/fragment_toolbar.xml

- Fixed centered text.
- Updated example design.
- close #
-
|Before|After|
|:--:|:--:|
| ![Screenshot_20210902_184027](https://user-images.githubusercontent.com/13705006/131821355-7af494da-b32d-4719-a929-5323c249f905.png) | ![Screenshot_20210902_183925](https://user-images.githubusercontent.com/13705006/131821306-253a4cd2-f5a4-40c7-871b-809917d02dd9.png) |

Updated Toolbar example

---

app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/res/layout-w720dp/activity_main.xml

- Implemented switching navigation view.  
- close #
-
|Portrait|Landscape|
|:--:|:--:|
| ![Screenshot_1632628621](https://user-images.githubusercontent.com/13705006/134793033-0b0fa866-553f-4c6a-8ffa-3593c97b2367.png) | ![Screenshot_1632628627](https://user-images.githubusercontent.com/13705006/134793036-f93979e0-f5b0-4d65-b4a7-30158016a7ac.png) |

Implemented switch navigation view

---

app/src/main/res/values/shape.xml

- Supported Material 3 Shape theming.
- Applied to default corner size.
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Supported Material3 shape

---

app/src/main/java/com/numero/material_gallery/MainActivity.kt
components/src/main/res/layout/fragment_extended_fab.xml

- Fixed Extended FAB elevation.
- Cleaned code.
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Clean code

---

README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Bump AGP version to 7.2.0-beta04

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/numero/material_gallery/MainActivity.kt

- Fixed splash implementation.
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed crash when launch app

---

app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/res/values/themes.xml

- Fixed #665  
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed visibility appbar

---

gradle.properties

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Adjust gradle.properties settings

---

components/src/main/java/com/numero/material_gallery/components/slider/SliderFragment.kt
components/src/main/res/layout/fragment_slider.xml

- Added labeled Slider example.  
- close #
-
|Before|After|
|:--:|:--:|
| ![Screenshot_20220429_092551](https://user-images.githubusercontent.com/13705006/165868036-eb6210a8-b30b-4743-926b-48ab8a71dabe.png) | ![Screenshot_20220429_092443](https://user-images.githubusercontent.com/13705006/165868032-7ba7ada4-eb1f-4934-8425-d00f06ab9ba8.png) |

Updated Slider example

---

components/src/main/java/com/numero/material_gallery/components/progressindicator/ProgressIndicatorFragment.kt
components/src/main/res/layout/fragment_progress_indicator.xml

- Updated ProgressIndicator example.
- close #
-
|Before|After|
|:--:|:--:|
|![Screenshot_20220429_101145](https://user-images.githubusercontent.com/13705006/165871144-3aa84b02-bd7a-4c5d-a447-87a00e6eedcd.png)  | ![Screenshot_20220429_101043](https://user-images.githubusercontent.com/13705006/165871143-9d0c1834-bb44-42cd-9020-116d6926c904.png) |

Updated ProgressIndicator example

---

app/src/main/res/values-night/themes.xml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Fixed crash when launched app

---

build.gradle
settings.gradle

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Cleaned plugin implementation

---

app/src/main/java/com/numero/material_gallery/MainActivity.kt
app/src/main/res/values-night-v29/themes.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values-v29/themes.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/themes.xml

- close #
-
|OS|Light|Dark|
|:--:|:--:|:--:|
| 27 | ![Screenshot_20220522_093341](https://user-images.githubusercontent.com/13705006/169673459-c9ef5a76-3275-4ce3-8a62-ed14533048b0.png) | ![Screenshot_20220522_093327](https://user-images.githubusercontent.com/13705006/169673457-dee7c6e9-7f17-48bd-a20b-09b09222d21b.png) |
| 32 | ![Screenshot_20220522_093403](https://user-images.githubusercontent.com/13705006/169673460-680863e8-6fec-46a8-be99-8f4da19ec8c9.png) | ![Screenshot_20220522_093416](https://user-images.githubusercontent.com/13705006/169673462-d427444c-112c-4df9-bce1-6db2f531658d.png)|

Implemented navigationBar edge to edge

---

app/src/main/java/com/numero/material_gallery/studies/StudiesFragment.kt
components/src/main/java/com/numero/material_gallery/components/ComponentListFragment.kt
components/src/main/java/com/numero/material_gallery/components/appbar/top/TopAppBarTypeFragment.kt

- close #
-
|Before|After|
|:--:|:--:|
| ![Screenshot_20220522_132154](https://user-images.githubusercontent.com/13705006/169678506-6f43fb55-94ff-4833-92e0-1da2f72a27a0.png) | ![Screenshot_20220522_132136](https://user-images.githubusercontent.com/13705006/169678504-ad979ea7-a58d-42ed-ac4c-f91f7375be85.png) |

Replaced DividerItemDecoration to MaterialDividerItemDecoration

---

build.gradle
components/src/main/java/com/numero/material_gallery/components/selection/SwitchFragment.kt
components/src/main/res/layout/fragment_switch.xml
studies/material3/src/main/res/layout/fragment_material3_component.xml

- Updated mdc-1.7.0-alpha02.
- Updated Switch example.
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated mdc and switch example

---

benchmark/build.gradle
build.gradle

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Bump macrobenchmark and profileinstaller lib version

---

.github/workflows/danger.yml

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Updated ruby version

---

.github/workflows/baseline-profiles.yml

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Added generate baseline profiles action

---

app/build.gradle
build.gradle
core/build.gradle
gradle/libs.versions.toml

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Replaced version catalog

---

app/src/main/AndroidManifest.xml
build.gradle

- 
- close #
- https://developer.android.com/about/versions/13/summary
|Before|After|
|:--:|:--:|
|  |  |

Bump SDK version to 33

---

components/src/main/res/layout/fragment_bottom_sheet.xml
components/src/main/res/layout/fragment_bottom_sheet_modal.xml

- close #
-
|Before|After|
|:--:|:--:|
|  |  |

[BottomSheet]Added sheet handler

---

components/src/main/res/layout/fragment_material_button.xml

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

[Button]Updated button style

---

components/src/main/java/com/numero/material_gallery/components/selection/CheckboxFragment.kt
components/src/main/res/layout/fragment_checkbox.xml

- Added checkbox styles.
- Added checkbox group example.
- close #
-
|Before|After|
|:--:|:--:|
| ![Screenshot_20230603_111729](https://github.com/NUmeroAndDev/MaterialGallery-android/assets/13705006/89cc881c-b7cb-4d36-9930-554ea4f7ba08) | ![Screenshot_20230603_111708](https://github.com/NUmeroAndDev/MaterialGallery-android/assets/13705006/00921663-804e-4351-9926-83ae14b223f7) |

[Checkbox]Updated example

---

components/src/main/res/layout/fragment_fab.xml

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

[FAB]Updated style

---

components/src/main/java/com/numero/material_gallery/components/ComponentListAdapter.kt
components/src/main/java/com/numero/material_gallery/components/ComponentListFragment.kt
components/src/main/java/com/numero/material_gallery/components/MaterialComponent.kt
components/src/main/java/com/numero/material_gallery/components/carousel/CarouselFragment.kt
components/src/main/res/layout/carousel_item.xml
components/src/main/res/layout/fragment_carousel.xml
components/src/main/res/navigation/nav_components.xml
components/src/main/res/values/strings.xml
components/src/main/res/values/transition_names.xml

[Carousel]Added sample

---

components/src/main/java/com/numero/material_gallery/components/ComponentListAdapter.kt
components/src/main/java/com/numero/material_gallery/components/ComponentListFragment.kt
components/src/main/java/com/numero/material_gallery/components/MaterialComponent.kt
components/src/main/java/com/numero/material_gallery/components/sheet/side/SideSheetFragment.kt
components/src/main/res/layout/fragment_side_sheet.xml
components/src/main/res/layout/side_sheet_modal_layout.xml
components/src/main/res/navigation/nav_components.xml
components/src/main/res/values/strings.xml
components/src/main/res/values/transition_names.xml
resource/src/main/res/drawable/ic_close.xml

- Added Side Sheet sample.
- close #
-

[Side sheet]Added sample

---

components/src/main/java/com/numero/material_gallery/components/ComponentListAdapter.kt
components/src/main/java/com/numero/material_gallery/components/ComponentListFragment.kt
components/src/main/java/com/numero/material_gallery/components/MaterialComponent.kt
components/src/main/java/com/numero/material_gallery/components/appbar/top/ToolbarFragment.kt
components/src/main/java/com/numero/material_gallery/components/badge/BadgeFragment.kt
components/src/main/java/com/numero/material_gallery/components/navigationbar/NavigationBarFragment.kt
components/src/main/java/com/numero/material_gallery/components/tab/TabFragment.kt
components/src/main/res/layout/fragment_badge.xml
components/src/main/res/layout/fragment_navigation_bar.xml
components/src/main/res/layout/fragment_tab.xml
components/src/main/res/navigation/nav_components.xml
components/src/main/res/values/strings.xml
components/src/main/res/values/transition_names.xml

Added Badge example

---

resource/src/main/res/mipmap-anydpi-v26/ic_launcher.xml

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Added Themed Icon

---

.github/workflows/baseline-profiles.yml
benchmark/build.gradle

-
- close #
-
|Before|After|
|:--:|:--:|
|  |  |

Changed to baseline profile generation using gradle managed device
